name: Build Padavan for Xiaomi Router 3G

on:
  release:
    types: published
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: started

env:
  TNAME: MI-R3G
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/hanwckf/rt-n56u /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: Edit .config
      run: |
        if [ ! -f /opt/rt-n56u/trunk/configs/templates/$TNAME.config ] ; then
        echo "$TNAME.config not found "
        exit 1
        fi
        cp -f /opt/rt-n56u/trunk/configs/templates/$TNAME.config .config
        chmod +x diy.sh
        ../diy.sh
        cp -f .config /opt/rt-n56u/trunk/

    - name: Build Firmware
      run: |
        cd /opt/rt-n56u/trunk
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/

    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
